name: Terraform Apply

permissions:
  id-token: write
  contents: read

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  terraform-apply-dev:
    runs-on: ubuntu-latest
    needs: []
    environment: dev
    name: Terraform Apply Dev

    steps:
      - name: Clone Repository (Latest)
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Terraform Plan
        uses: "./.github/templates/terraformPlanApply"
        with:
          apply: true
          tfenvname: dev

  terraform-apply-prod:
    runs-on: ubuntu-latest
    needs: [terraform-apply-dev]
    environment: prod
    name: Terraform Apply Prod

    steps:
      - name: Clone Repository (Latest)
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Terraform Plan
        uses: "./.github/templates/terraformPlanApply"
        with:
          apply: true
          tfenvname: prod
